
package login;

import Main.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Register extends PanelCustom {

    /**
     * Creates new form Register
     */
    

    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfName = new swing.TextField();
        tfUN = new swing.TextField();
        tfP = new swing.Password();
        button2 = new swing.Button();

        setBackground(new java.awt.Color(44, 40, 57));
        setPreferredSize(new java.awt.Dimension(300, 450));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");

        tfName.setForeground(new java.awt.Color(242, 242, 242));
        tfName.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        tfName.setHint("NAME");

        tfUN.setForeground(new java.awt.Color(242, 242, 242));
        tfUN.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        tfUN.setHint("USERNAME");

        tfP.setForeground(new java.awt.Color(242, 242, 242));
        tfP.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        tfP.setHint("PASSWORD");
        tfP.setName(""); // NOI18N
        tfP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(242, 242, 242));
        button2.setForeground(new java.awt.Color(44, 40, 57));
        button2.setText("Sign Up");
        button2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tfUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(tfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String name = tfName.getText();
        String username = tfUN.getText();
        String password = String.valueOf(tfP.getPassword());
        
        
        if(getAlpha()==0){
            
            if(name.isEmpty() || username.isEmpty() || password.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Fill up the form properly", "Error",JOptionPane.ERROR_MESSAGE);
        }else{
            //Start the Register process
            userRegister(name, username, password);
        }
        }
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button2;
    private javax.swing.JLabel jLabel1;
    private swing.TextField tfName;
    private swing.Password tfP;
    private swing.TextField tfUN;
    // End of variables declaration//GEN-END:variables

    private void userRegister(String name, String username, String password) {
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
        try {
            String sql = "INSERT INTO user (name, username, password) VALUES (?, ?, ?)";
            PreparedStatement st = (PreparedStatement) dbconn.prepareStatement(sql);
            
            st.setString(1, name);
            st.setString(2, username);
            st.setString(3, password);
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registration Done.", "Register",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Username Error", "Register",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            System.out.println("The Connection is not available");
        }
        
    }
}
